# Generated by Django 5.0.1 on 2024-01-26 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('description', models.TextField(max_length=1000)),
                ('image', models.ImageField(upload_to='product')),
                ('data', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
